services:
  postgres:
    container_name: postgres_posts_database
    image: postgres:17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: posts
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d posts" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: