services:
  postgres:
    env_file:
      - .env
    container_name: ${DOCKER_CONTAINER_NAME}
    image: postgres:17
    environment:
      POSTGRES_USER: ${DOCKER_USER}
      POSTGRES_PASSWORD: ${DOCKER_PASSWORD}
      POSTGRES_DB: ${DOCKER_DB}
    ports:
      - "${DOCKER_PORT}:${DOCKER_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: